### ISSUE TITLE
Yjs example fails running from several browsers on local machine (Chrome issue probably)

### ISSUE THREAD

**Issue by shillo-a** [tldraw/tldraw-yjs-example#1]
Hello!
I'm facing with strange behavior working with yjs example.
1. I open Firefox 115 and enter yjs example (everything works)
2. I open Chrome 114.0.5735.198 and enter yjs example (everything works)
3. I restart Chrome with yjs example and next error appears:

```
2PageMenu.tsx:111 Uncaught TypeError: Cannot read properties of undefined (reading 'id')
    at PageMenu2 (PageMenu.tsx:111:31)
    at renderWithHooks (react-dom.development.js:16305:18)
    at updateFunctionComponent (react-dom.development.js:19588:20)
    at beginWork (react-dom.development.js:21601:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27451:7)
    at performUnitOfWork (react-dom.development.js:26557:12)
    at workLoopSync (react-dom.development.js:26466:5)
```
4. I restart Firefox (everything works in Firefox, but not in Chrome)

I noticed that browsers working differently with ws closing on page refresh. 
Maybe this is the case?

**Comment by shillo-a** [comment]
Cheched next browsers - Microsoft Edge, Opera. Facing with the similar behavior like Chrome.

**Comment by shillo-a** [comment]
Hello! 
I recorded video with the behavior:
https://drive.google.com/file/d/1wGXUqEb-6NBut0gAzchKWgp_h-8alc2w/view?usp=drive_link

You could notice:
1. On first encounter everything works ok, but after refresh error appears
2. If two tabs opened in the browser, error doesn't appear even after refresh

**Comment by steveruizok** [comment]
Is this improved by https://github.com/tldraw/tldraw-yjs-example/pull/2?

**Comment by leolorenzoluis** [comment]
@steveruizok This is happening too with live partykit on my local and no multiple browsers in the same machine that is trying to connect.

```
TypeError: Cannot read properties of undefined (reading 'id')
    at PageMenu (webpack-internal:///(app-pages-browser)/./components/ui/tldraw/components/PageMenu/PageMenu.tsx:126:21)
    at renderWithHooks (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom-experimental/cjs/react-dom.development.js:10855:18)
    at updateFunctionComponent (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom-experimental/cjs/react-dom.development.js:15893:20)
    
```

**Comment by shillo-a** [comment]
@steveruizok, thank you for replying!
I launched latest version of `tldraw-yjs-example` and still facing with same issue.

I could show you error in real time by discord

**Comment by shillo-a** [comment]
@steveruizok, hello!
My college checked code and found that there could be issue with state sync with server. 

Particularly, commenting one of those leads to working app, but with restricted functionality:
- [Remove in mergeRemoteChanges](https://github.com/tldraw/tldraw-yjs-example/blob/main/src/useYjsStore.ts#L168C7-L168C50)
- [Create Page1 on the initialization, 88-100 lines](https://github.com/tldraw/tldraw-yjs-example/blob/main/src/useYjsStore.ts#L88)

**Comment by bitsofparag** [comment]
Facing the same issue on all browsers. It doesn't matter if only one client creates the document first or both together. The error seems to be finding the `currentPage` which is thrown as `undefined`

**Comment by steveruizok** [comment]
Hey, apologies for the delay here—these should be now fixed. 

We now:
- use the key/value store from y-utilities rather than a yMap for the shape records
- properly check the contents of the yjs store after sync, rather than after connect
- seed the store with an identical default state for each client, including ephemeral state records (e.g. instance state)

<img width="1382" alt="image" src="https://github.com/tldraw/tldraw-yjs-example/assets/23072548/bcfd7787-f7f0-44c7-bcf0-88087458fca0">

We also re-set the state when the hook re-runs, which should fix certain HMR issues.

**Comment by steveruizok** [comment]
Tagging for visibility @bitsofparag @leolorenzoluis @shillo-a

**Comment by steveruizok** [comment]
Pretty sure this one is solved now. Let me know if I need to reopen!
