### ISSUE TITLE
"dev" command does not work on windows

### ISSUE THREAD

**Issue by olaleykhan** [tldraw/tldraw-yjs-example#7]
the dev command `"dev": "concurrently \"vite\" \"HOST=localhost PORT=1234 npx y-websocket\" --kill-others",` does not work on Windows OS because well, it is written in Unix syntax.

can either add a separate command (dev:win) that works for Windows OS or use the cross-env package which is cleaner but is an extra overhead.

adding a short bootstrap guide in the README can also be beneficial.

**Comment by olaleykhan** [comment]
I can handle that and raise a PR if you don't mind

**Comment by steveruizok** [comment]
Could you add that as dev-win? Thanks!
